// Code generated by "esc -o data_gen.go -pkg main templates"; DO NOT EDIT.

package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/templates/hrpc-client-go.htmpl": {
		name:    "hrpc-client-go.htmpl",
		local:   "templates/hrpc-client-go.htmpl",
		size:    5103,
		modtime: 1611712741,
		compressed: `
H4sIAAAAAAAC/+RYW2/bNhR+z684FZKCKhT63Ugf1nTrijVNUa/YwzAUjHQkE6ZIjaSSBYb++0BS18ix
66bFCqwPjUCe2/edG5PtFk5vmEFYvgRiNS9XdZ7zf4DkXGDF7PqVu6TvWYkxRLTSyqoohqY52W7BoP2F
C5SsRCCm0lzaHKIzszgzdK2rlKaCo7S0UBGQDDXmQK8ry5U09I36wNINKzAOAXibzugpt1i6cKg/qYIU
bLcwDWlmyIvzslLaQiTRLtbWVlF/UihVCKSFEkwWVOli4cHc1Hn4GCS5WnBVWy6Go7y0I0vcrusbmqpy
USjNhWCLO7wxKt3gSMpFUOuRjZt7iyZqMfoz42BKvDNoO/SayQKBrlDf8jRAAgAYbq7QrlXWX7SXpxrN
W+mTqNEocYvZG/X7fYUtnRToW1nV1h95qh8oX9d2r/Z1bSfqY31WVSizFdoBV4iHjjJzWP66tmOFDjfK
rCNn9BnYON0kcHrrAu8tdZod6w7fBpomemiB5xOaQzlf/wZW193BzN+uvJwa1Ld9vfaHvikco6O+uPTt
MPSC76qBTuvYHZSbBozVdWph27MXGgpeuNKmwVx/5+JA/enjO6fGZeEvWtN5LVN4j3dj66TWohWN4cXE
7+BQo621hOfj6+F2CGnpPp+Pwto2yUSsj24JtRbDXTMO8/9a5q0Gz4FIZYEoDWTN2npZWY2sBBr7s5Xn
sT+LpzD7XJOuUsaJi52TcfF5ZaKDVMDy9rUXJC8GxsJZAqi10jFM0+97zXHu7x25fprSK6bNmgmi47l4
7kWfvQTJxQ5zo7qTXCSQl5b+7HznJEpVLTJwJJVMW84EaPy7RmOXcHYX+RjmDpuTuXlT9QG3W6r98UEZ
S5zLVWhcErmqXi4WZ2bRradRAmk3AgKhTeOEuu8o6Yz35R8nELGqEjxlbn8tVGrRnhufzygBvyToe7z7
iCxDTTy18bfl0OcRKmUsl8XX8ZdhjtqzSF+p7J5eCmWQzDUzZlnPc1iq1CH7SQjSa38PdBpZFtCZSkmD
x8FTfgy4mJ8/bIPtXNqF2pX9J1m2hR+gB0vfA2HdeRJfj7P1EIJMnKeT3QpuGQqDfkIxme2aRO3omo+t
+DtNqHTNJBwzpiomeUqiWvKyEliitJhF8VMQ7wD7ZKwxEC7Bgbs4n8H2BQUX53uwP46/dgVda0E/fXy3
XaVrLHEJ0Z2JEvhVuQnwcFYl8IHZ9RKi4wffaLH1D4UEPvezoH8w09eYs1rY15wJ1NT9IDVd+WcJiX1N
Pr17/H+o9Y6W2LHMLl2AJdvgtMT60ts1Lh7R6VMTzx0VyhcHiR8BEGZs2s/WnUKlKczU9Z9/uR3yiPgh
n75ild5z6/59TqBEY1iBww71Y/0qnO5YBMdmb/rCdAQ4pPFB2RuNbLNXqtl76/m8OO/wnRxnpXksTfs5
NShw8syfMeB+4y1NkYDaOLYvzl2cy0MsP1ObL6A3NMoBzvZe27VbQeF3WTKv/H2qu3enh+qtfttKejpU
3+oX5yG4/fkyKLMhYVxe/jD5mrzKps91F/SPxnmokZT+obnFbsQMC+QVl0zfX3UDyYH7DxAcOShOvmh0
tDuMy0u/+C8PPdFkduAvJ/8GAAD//x9Rp4fvEwAA
`,
	},

	"/templates/hrpc-server-go.htmpl": {
		name:    "hrpc-server-go.htmpl",
		local:   "templates/hrpc-server-go.htmpl",
		size:    8152,
		modtime: 1612055226,
		compressed: `
H4sIAAAAAAAC/+xZW2/bOBZ+969gjexCChR6d7FP2fahaXfaYqZNkAvmoSgGjHQsEZZIhaTiZgz99wFJ
UaZudpLJNHPzSxzykDznO9/5eJhsNkiC+o7mwEgBKEh5+x2juQRxC2IeorqezTYbdEAVFOj4FcJmpCTx
iqSANhu0pDmURGUnRALCp6WinEn8jp81JtqcFiUXCs1jzhR8VfN2gIFaZEqV2xHKF5RXiubboZTzNAec
8pywFHORLkrBFb+ulvaLZ0lVVl3jmBeLlAua52SxhmvJ4xWoe+2n7kqQiwRkLGipuCivRzfPiCg4uztK
4BZyXhbA1CITZbxoYGsgMwulRo3BWoJyYArCUkD4AsQtjS1CCCG0nfkIKuNJO9FMHgiQH5jeLhAgeX4L
yTt+eVdCkx2M8AdWVsoMmcz1Fp9Waufq00p1lvvrSVkCSy5AbeOy/mAv0fvtTyvlL3BxA0scON5Xi8bB
KkIHt9rxdie30qVGx7dCdT3v7HBLhCEoYTGF5JNmtg21rtGhn2Osmf+2HTjTbEAmacE+s3A2W1YsRpRR
FYRoY9xKiCLa36Y63upf3cnWcRBCGxje4StWECEzkgd6YTTlc2hDXprFL14hRvPmPP0pCaNxAEJYs3pm
IaTLDs9s0Z9+j5So3MAA8DFiHmhmt/XfDhq50JSSpaBMLdH8H/LC1gAKEhCwRFgHEW75pEvMW1zXiDIF
YkliaML5XdcBXaKAcYUCLlCQEfkmp8DUhRJACoRDM2YRaMfCrhPNRh46qK6DWH1FjTziN/ZnhAQ6bOPF
H97WdYQyIAkIibRq4vfml9BEUra2usassWYKCMEbUrhiyyWYOAhLxvxtAhwGFz5hHLxSKM4I63mNpmIc
BPA4Tyjrnvo0/rBkRMxsGU4y2q1vVKoth0EgRj66emV3uYdijRqGW0IPtct9PA0r7CZ6AHfK4T5Ktjuu
sLPXlLZNaJz7bLGsZyMZcYLTPf09YUkOAkklqlh5h9li6Ljezv1f15JbqbEL2gqL0Nry4xxkyZmEHwVV
Pk+uGBF3ZwKQ7RFws82lIEwuuShAtKZVmQpNMtQ2L/iqGfJZZZL3CdZTsQWyE4WRg4c5H5pqGAdui5gA
VQmG/nkP0y3Ax0hGnWEf22PP1a6Vg+Z4BJshYc6BJCfVcgnigv4Mxwj9+1//+W80MDPR+nZDszrqkczP
QZBN4xSic14pkEGIPn+RSlCWDqFzM5u+pE2qhvvMF64599oq7C5s54s2ct/nUf8QT68eE5/J5/vLy7Ng
lEQREnCDDpuZmwqk8rVGrqmKM32D3eCr8x/wGVGZP/8nbwZi/Wp6RBKPe0V1zZO7yImxfUBhzf7XeW6g
PeHJXVc1E1iCQG4Ov8m5hOBhepxhv2i1nERoHQ7MLMl7kt0n4ePzaI8wxLL3oH1vBf4N37bP/rU1vLUs
iv5mzwQIZbd8BSaZRqnjkZ4Kbhr/P4KUJIWp3rBnZPvBEecbLcqwZSz26BbE5jwcHPZBbQ8Nd4azRBlu
L8BJ+FzUrzzrYG8PMflgityGO33TrfO2cuwCUzIN0kHYZYRFwnWBg6208EXdruhjwy49/Ux8WjcOByF+
nSTB3MTG1JGupnmE5qQscxoTRTlb8FiBOpJGsObdw36KmsJZYyPugYs4nH2zuIbfRl4ETyWrujlvu6SB
Zmn5H1H9njZRo2oFWUEwfHpMCBOj+eCWHnn0/LFV3wLzq6SasnBPN/NNI+K2lxjmun1M9gplLdv0Zdj1
tq6hDdZGayLt9TOlKOX2/hm7L+5dAPpTyFR2ofn85fpO9YVj35mmJeViYqaRqMK76vSZa2mKorkBg3By
7T5Y/U9sKkeHFe60uxZAVpMW9eSMAezlkQtmdr/V9Uh0vefwUA3W0qq5A2j7sjLy0HYONmObeiRn0zmR
kEPnff1oCrW6bv+2wFc6ty+PNFDHu1L6gq/25HKkDnbURGf75r8ie0Vsv6DZqPSGT0nQvkCOW/FKhb8V
QkyzWIc1xYARwe6ku5DpNtu8Us+W7LWvKJ/gq7IPXK9eTqjuWpuCeZo0PrhEHpb/3fh/M5bs6ZwLmf6N
5gOIOujO92CnKe16wf/9RdG85wU761+3s27jNfJ47j0mKTP/bei+I8dfNd3od/ypzrvjfwkAAP//Pf7z
3dgfAAA=
`,
	},

	"/templates": {
		name:  "templates",
		local: `templates`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"templates": {
		_escData["/templates/hrpc-client-go.htmpl"],
		_escData["/templates/hrpc-server-go.htmpl"],
	},
}
