// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat/v1/chat.proto

#include "chat/v1/chat.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace protocol {
namespace chat {
namespace v1 {
}  // namespace v1
}  // namespace chat
}  // namespace protocol
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_chat_2fv1_2fchat_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_chat_2fv1_2fchat_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_chat_2fv1_2fchat_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_chat_2fv1_2fchat_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_chat_2fv1_2fchat_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022chat/v1/chat.proto\022\020protocol.chat.v1\032\033"
  "google/protobuf/empty.proto\032\033harmonytype"
  "s/v1/types.proto\032\025chat/v1/profile.proto\032"
  "\024chat/v1/guilds.proto\032\026chat/v1/channels."
  "proto\032\026chat/v1/messages.proto\032\024chat/v1/e"
  "motes.proto\032\031chat/v1/permissions.proto\032\027"
  "chat/v1/streaming.proto\032\025chat/v1/postbox"
  ".proto2\300)\n\013ChatService\022f\n\013CreateGuild\022$."
  "protocol.chat.v1.CreateGuildRequest\032%.pr"
  "otocol.chat.v1.CreateGuildResponse\"\n\232D\002\010"
  "\001\232D\002\032\000\022~\n\014CreateInvite\022%.protocol.chat.v"
  "1.CreateInviteRequest\032&.protocol.chat.v1"
  ".CreateInviteResponse\"\037\232D\002\010\001\232D\027\032\025invites"
  ".manage.create\022\202\001\n\rCreateChannel\022&.proto"
  "col.chat.v1.CreateChannelRequest\032\'.proto"
  "col.chat.v1.CreateChannelResponse\" \232D\002\010\001"
  "\232D\030\032\026channels.manage.create\022m\n\017CreateEmo"
  "tePack\022(.protocol.chat.v1.CreateEmotePac"
  "kRequest\032).protocol.chat.v1.CreateEmoteP"
  "ackResponse\"\005\232D\002\010\001\022d\n\014GetGuildList\022%.pro"
  "tocol.chat.v1.GetGuildListRequest\032&.prot"
  "ocol.chat.v1.GetGuildListResponse\"\005\232D\002\010\001"
  "\022~\n\023AddGuildToGuildList\022,.protocol.chat."
  "v1.AddGuildToGuildListRequest\032-.protocol"
  ".chat.v1.AddGuildToGuildListResponse\"\n\232D"
  "\002\010\001\232D\002\020\001\022\215\001\n\030RemoveGuildFromGuildList\0221."
  "protocol.chat.v1.RemoveGuildFromGuildLis"
  "tRequest\0322.protocol.chat.v1.RemoveGuildF"
  "romGuildListResponse\"\n\232D\002\010\001\232D\002\020\001\022X\n\010GetG"
  "uild\022!.protocol.chat.v1.GetGuildRequest\032"
  "\".protocol.chat.v1.GetGuildResponse\"\005\232D\002"
  "\010\001\022~\n\017GetGuildInvites\022(.protocol.chat.v1"
  ".GetGuildInvitesRequest\032).protocol.chat."
  "v1.GetGuildInvitesResponse\"\026\232D\002\010\001\232D\016\032\014in"
  "vites.view\022m\n\017GetGuildMembers\022(.protocol"
  ".chat.v1.GetGuildMembersRequest\032).protoc"
  "ol.chat.v1.GetGuildMembersResponse\"\005\232D\002\010"
  "\001\022k\n\020GetGuildChannels\022).protocol.chat.v1"
  ".GetGuildChannelsRequest\032*.protocol.chat"
  ".v1.GetGuildChannelsResponse\"\000\022\210\001\n\022GetCh"
  "annelMessages\022+.protocol.chat.v1.GetChan"
  "nelMessagesRequest\032,.protocol.chat.v1.Ge"
  "tChannelMessagesResponse\"\027\232D\002\010\001\232D\017\032\rmess"
  "ages.view\022p\n\nGetMessage\022#.protocol.chat."
  "v1.GetMessageRequest\032$.protocol.chat.v1."
  "GetMessageResponse\"\027\232D\002\010\001\232D\017\032\rmessages.v"
  "iew\022g\n\rGetEmotePacks\022&.protocol.chat.v1."
  "GetEmotePacksRequest\032\'.protocol.chat.v1."
  "GetEmotePacksResponse\"\005\232D\002\010\001\022v\n\022GetEmote"
  "PackEmotes\022+.protocol.chat.v1.GetEmotePa"
  "ckEmotesRequest\032,.protocol.chat.v1.GetEm"
  "otePackEmotesResponse\"\005\232D\002\010\001\022\214\001\n\026UpdateG"
  "uildInformation\022/.protocol.chat.v1.Updat"
  "eGuildInformationRequest\032\026.google.protob"
  "uf.Empty\")\232D\002\010\001\232D!\032\037guild.manage.change-"
  "information\022\223\001\n\030UpdateChannelInformation"
  "\0221.protocol.chat.v1.UpdateChannelInforma"
  "tionRequest\032\026.google.protobuf.Empty\",\232D\002"
  "\010\001\232D$\032\"channels.manage.change-informatio"
  "n\022y\n\022UpdateChannelOrder\022+.protocol.chat."
  "v1.UpdateChannelOrderRequest\032\026.google.pr"
  "otobuf.Empty\"\036\232D\002\010\001\232D\026\032\024channels.manage."
  "move\022h\n\rUpdateMessage\022&.protocol.chat.v1"
  ".UpdateMessageRequest\032\026.google.protobuf."
  "Empty\"\027\232D\002\010\001\232D\017\032\rmessages.send\022X\n\016AddEmo"
  "teToPack\022\'.protocol.chat.v1.AddEmoteToPa"
  "ckRequest\032\026.google.protobuf.Empty\"\005\232D\002\010\001"
  "\022j\n\013DeleteGuild\022$.protocol.chat.v1.Delet"
  "eGuildRequest\032\026.google.protobuf.Empty\"\035\232"
  "D\002\010\001\232D\025\032\023guild.manage.delete\022n\n\014DeleteIn"
  "vite\022%.protocol.chat.v1.DeleteInviteRequ"
  "est\032\026.google.protobuf.Empty\"\037\232D\002\010\001\232D\027\032\025i"
  "nvites.manage.delete\022q\n\rDeleteChannel\022&."
  "protocol.chat.v1.DeleteChannelRequest\032\026."
  "google.protobuf.Empty\" \232D\002\010\001\232D\030\032\026channel"
  "s.manage.delete\022V\n\rDeleteMessage\022&.proto"
  "col.chat.v1.DeleteMessageRequest\032\026.googl"
  "e.protobuf.Empty\"\005\232D\002\010\001\022b\n\023DeleteEmoteFr"
  "omPack\022,.protocol.chat.v1.DeleteEmoteFro"
  "mPackRequest\032\026.google.protobuf.Empty\"\005\232D"
  "\002\010\001\022Z\n\017DeleteEmotePack\022(.protocol.chat.v"
  "1.DeleteEmotePackRequest\032\026.google.protob"
  "uf.Empty\"\005\232D\002\010\001\022Z\n\017DequipEmotePack\022(.pro"
  "tocol.chat.v1.DequipEmotePackRequest\032\026.g"
  "oogle.protobuf.Empty\"\005\232D\002\010\001\022[\n\tJoinGuild"
  "\022\".protocol.chat.v1.JoinGuildRequest\032#.p"
  "rotocol.chat.v1.JoinGuildResponse\"\005\232D\002\010\001"
  "\022P\n\nLeaveGuild\022#.protocol.chat.v1.LeaveG"
  "uildRequest\032\026.google.protobuf.Empty\"\005\232D\002"
  "\010\001\022j\n\rTriggerAction\022&.protocol.chat.v1.T"
  "riggerActionRequest\032\026.google.protobuf.Em"
  "pty\"\031\232D\002\010\001\232D\021\032\017actions.trigger\022s\n\013SendMe"
  "ssage\022$.protocol.chat.v1.SendMessageRequ"
  "est\032%.protocol.chat.v1.SendMessageRespon"
  "se\"\027\232D\002\010\001\232D\017\032\rmessages.send\022\210\001\n\022QueryHas"
  "Permission\022).protocol.chat.v1.QueryPermi"
  "ssionsRequest\032*.protocol.chat.v1.QueryPe"
  "rmissionsResponse\"\033\232D\002\010\001\232D\023\032\021permissions"
  ".query\022s\n\016SetPermissions\022\'.protocol.chat"
  ".v1.SetPermissionsRequest\032\026.google.proto"
  "buf.Empty\" \232D\002\010\001\232D\030\032\026permissions.manage."
  "set\022\205\001\n\016GetPermissions\022\'.protocol.chat.v"
  "1.GetPermissionsRequest\032(.protocol.chat."
  "v1.GetPermissionsResponse\" \232D\002\010\001\232D\030\032\026per"
  "missions.manage.get\022i\n\010MoveRole\022!.protoc"
  "ol.chat.v1.MoveRoleRequest\032\".protocol.ch"
  "at.v1.MoveRoleResponse\"\026\232D\002\010\001\232D\016\032\014roles."
  "manage\022u\n\rGetGuildRoles\022&.protocol.chat."
  "v1.GetGuildRolesRequest\032\'.protocol.chat."
  "v1.GetGuildRolesResponse\"\023\232D\002\010\001\232D\013\032\trole"
  "s.get\022u\n\014AddGuildRole\022%.protocol.chat.v1"
  ".AddGuildRoleRequest\032&.protocol.chat.v1."
  "AddGuildRoleResponse\"\026\232D\002\010\001\232D\016\032\014roles.ma"
  "nage\022k\n\017ModifyGuildRole\022(.protocol.chat."
  "v1.ModifyGuildRoleRequest\032\026.google.proto"
  "buf.Empty\"\026\232D\002\010\001\232D\016\032\014roles.manage\022k\n\017Del"
  "eteGuildRole\022(.protocol.chat.v1.DeleteGu"
  "ildRoleRequest\032\026.google.protobuf.Empty\"\026"
  "\232D\002\010\001\232D\016\032\014roles.manage\022p\n\017ManageUserRole"
  "s\022(.protocol.chat.v1.ManageUserRolesRequ"
  "est\032\026.google.protobuf.Empty\"\033\232D\002\010\001\232D\023\032\021r"
  "oles.user.manage\022d\n\014GetUserRoles\022%.proto"
  "col.chat.v1.GetUserRolesRequest\032&.protoc"
  "ol.chat.v1.GetUserRolesResponse\"\005\232D\002\010\001\022Y"
  "\n\014StreamEvents\022%.protocol.chat.v1.Stream"
  "EventsRequest\032\027.protocol.chat.v1.Event\"\005"
  "\232D\002\010\001(\0010\001\022F\n\004Sync\022\035.protocol.chat.v1.Syn"
  "cRequest\032\033.protocol.chat.v1.SyncEvent\"\0000"
  "\001\022U\n\007GetUser\022 .protocol.chat.v1.GetUserR"
  "equest\032!.protocol.chat.v1.GetUserRespons"
  "e\"\005\232D\002\010\001\022m\n\017GetUserMetadata\022(.protocol.c"
  "hat.v1.GetUserMetadataRequest\032).protocol"
  ".chat.v1.GetUserMetadataResponse\"\005\232D\002\010\001\022"
  "V\n\rProfileUpdate\022&.protocol.chat.v1.Prof"
  "ileUpdateRequest\032\026.google.protobuf.Empty"
  "\"\005\232D\002\010\001\022Z\n\006Typing\022\037.protocol.chat.v1.Typ"
  "ingRequest\032\026.google.protobuf.Empty\"\027\232D\002\010"
  "\001\232D\017\032\rmessages.send\022d\n\014PreviewGuild\022%.pr"
  "otocol.chat.v1.PreviewGuildRequest\032&.pro"
  "tocol.chat.v1.PreviewGuildResponse\"\005\232D\002\010"
  "\000B3Z1github.com/harmony-development/lega"
  "to/gen/chat/v1b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_chat_2fv1_2fchat_2eproto_deps[10] = {
  &::descriptor_table_chat_2fv1_2fchannels_2eproto,
  &::descriptor_table_chat_2fv1_2femotes_2eproto,
  &::descriptor_table_chat_2fv1_2fguilds_2eproto,
  &::descriptor_table_chat_2fv1_2fmessages_2eproto,
  &::descriptor_table_chat_2fv1_2fpermissions_2eproto,
  &::descriptor_table_chat_2fv1_2fpostbox_2eproto,
  &::descriptor_table_chat_2fv1_2fprofile_2eproto,
  &::descriptor_table_chat_2fv1_2fstreaming_2eproto,
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
  &::descriptor_table_harmonytypes_2fv1_2ftypes_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_chat_2fv1_2fchat_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_chat_2fv1_2fchat_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_chat_2fv1_2fchat_2eproto = {
  false, false, descriptor_table_protodef_chat_2fv1_2fchat_2eproto, "chat/v1/chat.proto", 5662,
  &descriptor_table_chat_2fv1_2fchat_2eproto_once, descriptor_table_chat_2fv1_2fchat_2eproto_sccs, descriptor_table_chat_2fv1_2fchat_2eproto_deps, 0, 10,
  schemas, file_default_instances, TableStruct_chat_2fv1_2fchat_2eproto::offsets,
  file_level_metadata_chat_2fv1_2fchat_2eproto, 0, file_level_enum_descriptors_chat_2fv1_2fchat_2eproto, file_level_service_descriptors_chat_2fv1_2fchat_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_chat_2fv1_2fchat_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_chat_2fv1_2fchat_2eproto)), true);
namespace protocol {
namespace chat {
namespace v1 {

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace chat
}  // namespace protocol
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
